### ISSUE TITLE
Virus detected in files

### ISSUE THREAD

**Issue by EtherTechDev** [Kreeblah/XGecu_Software#5]
When I test the XGecu installer files (the unzippedone ) on VirusTotal.com, it detects viruses in the files from multiple places.
Seems to affect all files on version 12, I downloaded and tested the latest (XgproV1263_Setup.exe).
1. Bkav Pro detects W32.AIDetectMalware,
2. Cybereason detects Malicious.9e352c.
Version 11 files does not to be afffected.
I tried to contact the manufacturer and asked about the detection, I have not received any answer.
Should I be concerned?

**Comment by Kreeblah** [comment]
That can happen sometimes with files, particularly self-extracting files.  Looks like Cybereason fixed their detection (at least for 12.63) and isn't detecting it as malicious any longer.

Things that aren't listed as specific named threats are detected by heuristics engines, and those may or may not be accurate.

It comes down to a judgment call.  Given that it's currently only one engine at this point detecting anything, and it's detecting it via a heuristics-based detection (I'd be much more concerned if it were several engines, especially if they had a specific, named threat that they were detecting), I don't personally see that as likely to be an issue, but not everybody's risk appetite is the same.
