### ISSUE TITLE
Extracting T48 firmware version 01.1.00 (0x100)

### ISSUE THREAD

**Issue by DavidGriffith** [Kreeblah/XGecu_Software#7]
My T48 appears to have the very first firmware made for it: 01.1.00 (0x100).  I don't see that one archived anywhere, so I'd like to extract the firmware.  How do I do that?

**Comment by Kreeblah** [comment]
Huh.  That's a really good question.  I don't think there's any official way to extract firmware from these things.  It might require reading the flash chips directly.

As far as how feasible that is, though, I don't know.  I have a T48 and a T56, but I haven't actually disassembled either of them to see what they've done with the board layout.

**Comment by DavidGriffith** [comment]
This firmware version seems to be a consequence of the firmware not being valid or blank and therefore doesn't actually exist.  Fortunately, this condition doesn't brick the T48.
